// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteFilesByIdData, DeleteFilesByIdResponses, GetFilesByIdDownloadData, GetFilesByIdDownloadResponses, GetFilesData, GetFilesResponses, GetFolderByParentIdParentData, GetFolderByParentIdParentErrors, GetFolderByParentIdParentResponses, GetFoldersByParentIdData, GetFoldersByParentIdResponses, GetFoldersByParentIdStatsData, GetFoldersByParentIdStatsErrors, GetFoldersByParentIdStatsResponses, GetMeData, GetMeErrors, GetMeResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostFilesUnzipData, PostFilesUnzipErrors, PostFilesUnzipResponses, PostFilesUploadData, PostFilesUploadResponses, PostFoldersData, PostFoldersErrors, PostFoldersResponses, PostMeEmailData, PostMeEmailErrors, PostMeEmailResponses, PostMePasswordData, PostMePasswordErrors, PostMePasswordResponses, PostMeProfileData, PostMeProfileErrors, PostMeProfileResponses, PostMoveByIdData, PostMoveByIdErrors, PostMoveByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout (revoke refresh token)
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostAuthLogoutData, ThrowOnError>) => (options.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
    url: '/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh tokens
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostAuthRefreshData, ThrowOnError>) => (options.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List files/folders
 */
export const getFiles = <ThrowOnError extends boolean = false>(options?: Options<GetFilesData, ThrowOnError>) => (options?.client ?? client).get<GetFilesResponses, unknown, ThrowOnError>({ url: '/files', ...options });

/**
 * Delete node (file or folder)
 */
export const deleteFilesById = <ThrowOnError extends boolean = false>(options: Options<DeleteFilesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteFilesByIdResponses, unknown, ThrowOnError>({ url: '/files/{id}', ...options });

/**
 * Download file
 */
export const getFilesByIdDownload = <ThrowOnError extends boolean = false>(options: Options<GetFilesByIdDownloadData, ThrowOnError>) => (options.client ?? client).get<GetFilesByIdDownloadResponses, unknown, ThrowOnError>({ url: '/files/{id}/download', ...options });

/**
 * Unzip uploaded ZIP archive
 */
export const postFilesUnzip = <ThrowOnError extends boolean = false>(options: Options<PostFilesUnzipData, ThrowOnError>) => (options.client ?? client).post<PostFilesUnzipResponses, PostFilesUnzipErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/files/unzip',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Upload file
 */
export const postFilesUpload = <ThrowOnError extends boolean = false>(options: Options<PostFilesUploadData, ThrowOnError>) => (options.client ?? client).post<PostFilesUploadResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/files/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get immediate parent of a folder
 */
export const getFolderByParentIdParent = <ThrowOnError extends boolean = false>(options: Options<GetFolderByParentIdParentData, ThrowOnError>) => (options.client ?? client).get<GetFolderByParentIdParentResponses, GetFolderByParentIdParentErrors, ThrowOnError>({ url: '/folder/{parent_id}/parent', ...options });

/**
 * Create folder
 */
export const postFolders = <ThrowOnError extends boolean = false>(options: Options<PostFoldersData, ThrowOnError>) => (options.client ?? client).post<PostFoldersResponses, PostFoldersErrors, ThrowOnError>({
    url: '/folders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List files/folders under a folder
 */
export const getFoldersByParentId = <ThrowOnError extends boolean = false>(options: Options<GetFoldersByParentIdData, ThrowOnError>) => (options.client ?? client).get<GetFoldersByParentIdResponses, unknown, ThrowOnError>({ url: '/folders/{parent_id}', ...options });

/**
 * Get folder stats (items count and breakdown by file extension)
 */
export const getFoldersByParentIdStats = <ThrowOnError extends boolean = false>(options: Options<GetFoldersByParentIdStatsData, ThrowOnError>) => (options.client ?? client).get<GetFoldersByParentIdStatsResponses, GetFoldersByParentIdStatsErrors, ThrowOnError>({ url: '/folders/{parent_id}/stats', ...options });

/**
 * Get current user
 *
 * Returns the authenticated user's profile information extracted from the JWT.
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({ url: '/me', ...options });

/**
 * Change email
 *
 * Change the authenticated user's email. Requires current password for confirmation.
 */
export const postMeEmail = <ThrowOnError extends boolean = false>(options: Options<PostMeEmailData, ThrowOnError>) => (options.client ?? client).post<PostMeEmailResponses, PostMeEmailErrors, ThrowOnError>({
    url: '/me/email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change password
 *
 * Change the authenticated user's password. Requires current password for confirmation. This will not return a body (204).
 */
export const postMePassword = <ThrowOnError extends boolean = false>(options: Options<PostMePasswordData, ThrowOnError>) => (options.client ?? client).post<PostMePasswordResponses, PostMePasswordErrors, ThrowOnError>({
    url: '/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update profile (name or avatar)
 *
 * Update the authenticated user's profile. Accepts multipart/form-data for avatar upload or a JSON body with `name`.
 */
export const postMeProfile = <ThrowOnError extends boolean = false>(options?: Options<PostMeProfileData, ThrowOnError>) => (options?.client ?? client).post<PostMeProfileResponses, PostMeProfileErrors, ThrowOnError>({
    url: '/me/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Move node (file or folder) to another parent (or root)
 */
export const postMoveById = <ThrowOnError extends boolean = false>(options: Options<PostMoveByIdData, ThrowOnError>) => (options.client ?? client).post<PostMoveByIdResponses, PostMoveByIdErrors, ThrowOnError>({
    url: '/move/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
