// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

export type ControllersFolderStat = {
    count?: number;
    /**
     * percentage (0-100), rounded to 2 decimals
     */
    percent?: number;
    /**
     * e.g. "png", "jpg", "folder", "unknown"
     */
    type?: string;
};

export type ControllersFolderStatsResponse = {
    parent_id?: string;
    stats?: Array<ControllersFolderStat>;
    total_items?: number;
};

export type ControllersUnzipResponse = {
    created_count?: number;
    created_nodes?: Array<ModelsNode>;
    created_paths?: Array<string>;
    message?: string;
    root_parent_id?: string;
    timestamp?: string;
};

export type ControllersChangeEmailReq = {
    current_password: string;
    new_email: string;
};

export type ControllersChangePasswordReq = {
    current_password: string;
    new_password: string;
};

export type ControllersCreateFolderReq = {
    name: string;
    parent_id?: string;
};

export type ControllersLoginReq = {
    email: string;
    password: string;
};

export type ControllersLoginRes = {
    access_token?: string;
    refresh_token?: string;
};

export type ControllersLogoutReq = {
    refresh_token: string;
};

export type ControllersMoveReq = {
    /**
     * 空文字列で root に移動
     */
    parent_id?: string;
};

export type ControllersRefreshReq = {
    refresh_token: string;
};

export type ControllersRefreshRes = {
    access_token?: string;
    refresh_token?: string;
};

export type ControllersRegisterReq = {
    email: string;
    name?: string;
    password: string;
};

export type ControllersUserRes = {
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    updated_at?: string;
};

export type ModelsNode = {
    created_at?: string;
    id?: string;
    mime?: string;
    name?: string;
    owner_id?: string;
    /**
     * root: empty
     */
    parent_id?: string;
    /**
     * local storage path for files
     */
    path?: string;
    /**
     * bytes for files
     */
    size?: number;
    /**
     * "file" | "folder"
     */
    type?: string;
    updated_at?: string;
};

export type PostAuthLoginData = {
    /**
     * email and password
     */
    body: ControllersLoginReq;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: ControllersLoginRes;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    /**
     * refresh token to revoke
     */
    body: ControllersLogoutReq;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthRefreshData = {
    /**
     * refresh token
     */
    body: ControllersRefreshReq;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: ControllersRefreshRes;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthRegisterData = {
    /**
     * email and password
     */
    body: ControllersRegisterReq;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Created
     */
    201: {
        [key: string]: unknown;
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * parent id (optional)
         */
        parent_id?: string;
    };
    url: '/files';
};

export type GetFilesResponses = {
    /**
     * OK
     */
    200: Array<ModelsNode>;
};

export type GetFilesResponse = GetFilesResponses[keyof GetFilesResponses];

export type DeleteFilesByIdData = {
    body?: never;
    path: {
        /**
         * node id
         */
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type DeleteFilesByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetFilesByIdDownloadData = {
    body?: never;
    path: {
        /**
         * file id
         */
        id: string;
    };
    query?: never;
    url: '/files/{id}/download';
};

export type GetFilesByIdDownloadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostFilesUnzipData = {
    body: {
        /**
         * parent folder id
         */
        parent_id?: string;
        /**
         * zip file to upload
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/unzip';
};

export type PostFilesUnzipErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostFilesUnzipError = PostFilesUnzipErrors[keyof PostFilesUnzipErrors];

export type PostFilesUnzipResponses = {
    /**
     * Created
     */
    201: ControllersUnzipResponse;
};

export type PostFilesUnzipResponse = PostFilesUnzipResponses[keyof PostFilesUnzipResponses];

export type PostFilesUploadData = {
    body: {
        /**
         * parent folder id
         */
        parent_id?: string;
        /**
         * file to upload
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/files/upload';
};

export type PostFilesUploadResponses = {
    /**
     * Created
     */
    201: ModelsNode;
};

export type PostFilesUploadResponse = PostFilesUploadResponses[keyof PostFilesUploadResponses];

export type GetFolderByParentIdParentData = {
    body?: never;
    path: {
        /**
         * folder id (the folder to get the parent of)
         */
        parent_id: string;
    };
    query?: never;
    url: '/folder/{parent_id}/parent';
};

export type GetFolderByParentIdParentErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetFolderByParentIdParentError = GetFolderByParentIdParentErrors[keyof GetFolderByParentIdParentErrors];

export type GetFolderByParentIdParentResponses = {
    /**
     * parent node, or null if none
     */
    200: ModelsNode;
};

export type GetFolderByParentIdParentResponse = GetFolderByParentIdParentResponses[keyof GetFolderByParentIdParentResponses];

export type PostFoldersData = {
    /**
     * name and optional parent
     */
    body: ControllersCreateFolderReq;
    path?: never;
    query?: never;
    url: '/folders';
};

export type PostFoldersErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostFoldersError = PostFoldersErrors[keyof PostFoldersErrors];

export type PostFoldersResponses = {
    /**
     * Created
     */
    201: ModelsNode;
};

export type PostFoldersResponse = PostFoldersResponses[keyof PostFoldersResponses];

export type GetFoldersByParentIdData = {
    body?: never;
    path: {
        /**
         * parent folder id
         */
        parent_id: string;
    };
    query?: never;
    url: '/folders/{parent_id}';
};

export type GetFoldersByParentIdResponses = {
    /**
     * OK
     */
    200: Array<ModelsNode>;
};

export type GetFoldersByParentIdResponse = GetFoldersByParentIdResponses[keyof GetFoldersByParentIdResponses];

export type GetFoldersByParentIdStatsData = {
    body?: never;
    path: {
        /**
         * parent folder id (use empty string for root)
         */
        parent_id: string;
    };
    query?: {
        /**
         * include nested children recursively
         */
        recursive?: boolean;
    };
    url: '/folders/{parent_id}/stats';
};

export type GetFoldersByParentIdStatsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetFoldersByParentIdStatsError = GetFoldersByParentIdStatsErrors[keyof GetFoldersByParentIdStatsErrors];

export type GetFoldersByParentIdStatsResponses = {
    /**
     * OK
     */
    200: ControllersFolderStatsResponse;
};

export type GetFoldersByParentIdStatsResponse = GetFoldersByParentIdStatsResponses[keyof GetFoldersByParentIdStatsResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: ControllersUserRes;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type PostMeEmailData = {
    /**
     * current password and new email
     */
    body: ControllersChangeEmailReq;
    path?: never;
    query?: never;
    url: '/me/email';
};

export type PostMeEmailErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostMeEmailError = PostMeEmailErrors[keyof PostMeEmailErrors];

export type PostMeEmailResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostMeEmailResponse = PostMeEmailResponses[keyof PostMeEmailResponses];

export type PostMePasswordData = {
    /**
     * current password and new password
     */
    body: ControllersChangePasswordReq;
    path?: never;
    query?: never;
    url: '/me/password';
};

export type PostMePasswordErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostMePasswordError = PostMePasswordErrors[keyof PostMePasswordErrors];

export type PostMePasswordResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostMeProfileData = {
    body?: {
        /**
         * Display name
         */
        name?: string;
        /**
         * Avatar image file (multipart/form-data)
         */
        avatar?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/me/profile';
};

export type PostMeProfileErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostMeProfileError = PostMeProfileErrors[keyof PostMeProfileErrors];

export type PostMeProfileResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostMeProfileResponse = PostMeProfileResponses[keyof PostMeProfileResponses];

export type PostMoveByIdData = {
    /**
     * new parent id (empty string for root)
     */
    body: ControllersMoveReq;
    path: {
        /**
         * node id to move
         */
        id: string;
    };
    query?: never;
    url: '/move/{id}';
};

export type PostMoveByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostMoveByIdError = PostMoveByIdErrors[keyof PostMoveByIdErrors];

export type PostMoveByIdResponses = {
    /**
     * OK
     */
    200: ModelsNode;
};

export type PostMoveByIdResponse = PostMoveByIdResponses[keyof PostMoveByIdResponses];
