// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "server/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FileRepository is an autogenerated mock type for the FileRepository type
type FileRepository struct {
	mock.Mock
}

// CreateNode provides a mock function with given fields: n
func (_m *FileRepository) CreateNode(n *models.Node) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for CreateNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Node) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteNode provides a mock function with given fields: id
func (_m *FileRepository) DeleteNode(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindNodeByID provides a mock function with given fields: id
func (_m *FileRepository) FindNodeByID(id string) (*models.Node, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByID")
	}

	var r0 *models.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Node, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Node); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChildren provides a mock function with given fields: ownerID, parentID
func (_m *FileRepository) ListChildren(ownerID string, parentID string) ([]*models.Node, error) {
	ret := _m.Called(ownerID, parentID)

	if len(ret) == 0 {
		panic("no return value specified for ListChildren")
	}

	var r0 []*models.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*models.Node, error)); ok {
		return rf(ownerID, parentID)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*models.Node); ok {
		r0 = rf(ownerID, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(ownerID, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNode provides a mock function with given fields: n
func (_m *FileRepository) UpdateNode(n *models.Node) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Node) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNodeParent provides a mock function with given fields: ownerID, nodeID, parentID
func (_m *FileRepository) UpdateNodeParent(ownerID string, nodeID string, parentID string) error {
	ret := _m.Called(ownerID, nodeID, parentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNodeParent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(ownerID, nodeID, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFileRepository creates a new instance of FileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileRepository {
	mock := &FileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
